# .github/workflows/run_script.yml

name: Solve Today's Letter-Boxed

on:
  schedule:
    - cron: '2 8 * * *' # This cron expression means the script will run every day at midnight (UTC)
  push:
    branches:
      - master


jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          
      - name: Run script and capture output file name
        id: run-script
        run: |
          file_name=$(python solver.py)
          echo "::set-output name=file_name::$file_name"

      - name: Create solves directory
        run: mkdir -p solves

      - name: Copy and rename file to today's file
        run: |
          cp ${{ steps.run-script.outputs.file_name }} solves/todays.txt

      - name: Move output file to solves directory
        run: |
          mv ${{ steps.run-script.outputs.file_name }} solves/
          
      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Check for changes
        id: check_changes
        run: |
          git add solves/
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit" > no_changes
          else
            echo "Changes to commit" > changes
          fi

      - name: Commit and push changes
        if: steps.check_changes.outputs.changes == 'Changes to commit'
        run: |
          git commit -m "Add output file and today's puzzle to solves directory"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Handle no changes
        if: steps.check_changes.outputs.changes == 'No changes to commit'
        run: echo "No changes to commit, skipping commit step."
